### ISSUE TITLE
Precommit hook hangs sometimes

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/peril#2]
On certain commits, the precommit hook used to lint and run tests hangs on the`prettier` run. For example:

```
➜  rxswiftcommunity-peril git:(changelog) ✗ git commit -am "Cleanup from #1."
husky > npm run -s precommit (node v8.4.0)

 ❯ Running tasks for *.@(ts|tsx)
   ⠋ yarn prettier --write
     jest
     git add
 ↓ Running tasks for *.json [skipped]
   → No staged files match *.json
```

Haven't been able to find anything online about this hanging behaviour. I looked through open files and stuff and couldn't immediately see any problems. Not sure. 

We can bypass for now by running `git commit --no-verify` but it does need to be fixed before we can scale our use of Peril up.

**Comment by orta** [comment]
o.0

Any idea what files that is? I've never seen prettier be unreliable

**Comment by ashfurrow** [comment]
It's `pr.ts`, looks like. This _could_ be something on my system too. I'll look into it further.

**Comment by ashfurrow** [comment]
This is happening for all files, seems like. Google isn't being helpful – a computer restart hasn't helped either. Hmm.

**Comment by ashfurrow** [comment]
I've worked in this repo lately and this problem hasn't happened. Closing.
